// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/awesome.proto

package com.parking.protobuf;

public final class Awesome {
  private Awesome() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AwesomeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.parking.protobuf.AwesomeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    java.lang.String getAwesomeField();
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    com.google.protobuf.ByteString
        getAwesomeFieldBytes();
  }
  /**
   * Protobuf type {@code com.parking.protobuf.AwesomeMessage}
   */
  public  static final class AwesomeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.parking.protobuf.AwesomeMessage)
      AwesomeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AwesomeMessage.newBuilder() to construct.
    private AwesomeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AwesomeMessage() {
      awesomeField_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AwesomeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              awesomeField_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.parking.protobuf.Awesome.internal_static_com_parking_protobuf_AwesomeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.parking.protobuf.Awesome.internal_static_com_parking_protobuf_AwesomeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.parking.protobuf.Awesome.AwesomeMessage.class, com.parking.protobuf.Awesome.AwesomeMessage.Builder.class);
    }

    public static final int AWESOME_FIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object awesomeField_;
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    public java.lang.String getAwesomeField() {
      java.lang.Object ref = awesomeField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        awesomeField_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAwesomeFieldBytes() {
      java.lang.Object ref = awesomeField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        awesomeField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAwesomeFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, awesomeField_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAwesomeFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, awesomeField_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.parking.protobuf.Awesome.AwesomeMessage)) {
        return super.equals(obj);
      }
      com.parking.protobuf.Awesome.AwesomeMessage other = (com.parking.protobuf.Awesome.AwesomeMessage) obj;

      boolean result = true;
      result = result && getAwesomeField()
          .equals(other.getAwesomeField());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AWESOME_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getAwesomeField().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.parking.protobuf.Awesome.AwesomeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.parking.protobuf.AwesomeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.parking.protobuf.AwesomeMessage)
        com.parking.protobuf.Awesome.AwesomeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.parking.protobuf.Awesome.internal_static_com_parking_protobuf_AwesomeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.parking.protobuf.Awesome.internal_static_com_parking_protobuf_AwesomeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.parking.protobuf.Awesome.AwesomeMessage.class, com.parking.protobuf.Awesome.AwesomeMessage.Builder.class);
      }

      // Construct using com.parking.protobuf.Awesome.AwesomeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        awesomeField_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.parking.protobuf.Awesome.internal_static_com_parking_protobuf_AwesomeMessage_descriptor;
      }

      public com.parking.protobuf.Awesome.AwesomeMessage getDefaultInstanceForType() {
        return com.parking.protobuf.Awesome.AwesomeMessage.getDefaultInstance();
      }

      public com.parking.protobuf.Awesome.AwesomeMessage build() {
        com.parking.protobuf.Awesome.AwesomeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.parking.protobuf.Awesome.AwesomeMessage buildPartial() {
        com.parking.protobuf.Awesome.AwesomeMessage result = new com.parking.protobuf.Awesome.AwesomeMessage(this);
        result.awesomeField_ = awesomeField_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.parking.protobuf.Awesome.AwesomeMessage) {
          return mergeFrom((com.parking.protobuf.Awesome.AwesomeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.parking.protobuf.Awesome.AwesomeMessage other) {
        if (other == com.parking.protobuf.Awesome.AwesomeMessage.getDefaultInstance()) return this;
        if (!other.getAwesomeField().isEmpty()) {
          awesomeField_ = other.awesomeField_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.parking.protobuf.Awesome.AwesomeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.parking.protobuf.Awesome.AwesomeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object awesomeField_ = "";
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public java.lang.String getAwesomeField() {
        java.lang.Object ref = awesomeField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          awesomeField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAwesomeFieldBytes() {
        java.lang.Object ref = awesomeField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          awesomeField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder setAwesomeField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        awesomeField_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder clearAwesomeField() {
        
        awesomeField_ = getDefaultInstance().getAwesomeField();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder setAwesomeFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        awesomeField_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.parking.protobuf.AwesomeMessage)
    }

    // @@protoc_insertion_point(class_scope:com.parking.protobuf.AwesomeMessage)
    private static final com.parking.protobuf.Awesome.AwesomeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.parking.protobuf.Awesome.AwesomeMessage();
    }

    public static com.parking.protobuf.Awesome.AwesomeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AwesomeMessage>
        PARSER = new com.google.protobuf.AbstractParser<AwesomeMessage>() {
      public AwesomeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AwesomeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AwesomeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AwesomeMessage> getParserForType() {
      return PARSER;
    }

    public com.parking.protobuf.Awesome.AwesomeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_parking_protobuf_AwesomeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_parking_protobuf_AwesomeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protobuf/awesome.proto\022\024com.parking.pr" +
      "otobuf\"\'\n\016AwesomeMessage\022\025\n\rawesome_fiel" +
      "d\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_parking_protobuf_AwesomeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_parking_protobuf_AwesomeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_parking_protobuf_AwesomeMessage_descriptor,
        new java.lang.String[] { "AwesomeField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
