// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/base.proto

package com.parking.protobuf;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.parking.protobuf.NetError)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    int getCode();
  }
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * Protobuf type {@code com.parking.protobuf.NetError}
   */
  public  static final class NetError extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.parking.protobuf.NetError)
      NetErrorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetError.newBuilder() to construct.
    private NetError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetError() {
      code_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetError(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetError_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.parking.protobuf.Base.NetError.class, com.parking.protobuf.Base.NetError.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeUInt32(1, code_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.parking.protobuf.Base.NetError)) {
        return super.equals(obj);
      }
      com.parking.protobuf.Base.NetError other = (com.parking.protobuf.Base.NetError) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.parking.protobuf.Base.NetError parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.parking.protobuf.Base.NetError prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * Protobuf type {@code com.parking.protobuf.NetError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.parking.protobuf.NetError)
        com.parking.protobuf.Base.NetErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetError_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.parking.protobuf.Base.NetError.class, com.parking.protobuf.Base.NetError.Builder.class);
      }

      // Construct using com.parking.protobuf.Base.NetError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetError_descriptor;
      }

      public com.parking.protobuf.Base.NetError getDefaultInstanceForType() {
        return com.parking.protobuf.Base.NetError.getDefaultInstance();
      }

      public com.parking.protobuf.Base.NetError build() {
        com.parking.protobuf.Base.NetError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.parking.protobuf.Base.NetError buildPartial() {
        com.parking.protobuf.Base.NetError result = new com.parking.protobuf.Base.NetError(this);
        result.code_ = code_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.parking.protobuf.Base.NetError) {
          return mergeFrom((com.parking.protobuf.Base.NetError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.parking.protobuf.Base.NetError other) {
        if (other == com.parking.protobuf.Base.NetError.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.parking.protobuf.Base.NetError parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.parking.protobuf.Base.NetError) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>uint32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>uint32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>uint32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.parking.protobuf.NetError)
    }

    // @@protoc_insertion_point(class_scope:com.parking.protobuf.NetError)
    private static final com.parking.protobuf.Base.NetError DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.parking.protobuf.Base.NetError();
    }

    public static com.parking.protobuf.Base.NetError getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetError>
        PARSER = new com.google.protobuf.AbstractParser<NetError>() {
      public NetError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetError(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetError> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetError> getParserForType() {
      return PARSER;
    }

    public com.parking.protobuf.Base.NetError getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.parking.protobuf.NetHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户编号
     * </pre>
     *
     * <code>uint64 uid = 1;</code>
     */
    long getUid();

    /**
     * <pre>
     * 协议名称
     * </pre>
     *
     * <code>string proto = 2;</code>
     */
    java.lang.String getProto();
    /**
     * <pre>
     * 协议名称
     * </pre>
     *
     * <code>string proto = 2;</code>
     */
    com.google.protobuf.ByteString
        getProtoBytes();
  }
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * Protobuf type {@code com.parking.protobuf.NetHeader}
   */
  public  static final class NetHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.parking.protobuf.NetHeader)
      NetHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetHeader.newBuilder() to construct.
    private NetHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetHeader() {
      uid_ = 0L;
      proto_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              proto_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.parking.protobuf.Base.NetHeader.class, com.parking.protobuf.Base.NetHeader.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     * 用户编号
     * </pre>
     *
     * <code>uint64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int PROTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object proto_;
    /**
     * <pre>
     * 协议名称
     * </pre>
     *
     * <code>string proto = 2;</code>
     */
    public java.lang.String getProto() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proto_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 协议名称
     * </pre>
     *
     * <code>string proto = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeUInt64(1, uid_);
      }
      if (!getProtoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, proto_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, uid_);
      }
      if (!getProtoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, proto_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.parking.protobuf.Base.NetHeader)) {
        return super.equals(obj);
      }
      com.parking.protobuf.Base.NetHeader other = (com.parking.protobuf.Base.NetHeader) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getProto()
          .equals(other.getProto());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + PROTO_FIELD_NUMBER;
      hash = (53 * hash) + getProto().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.parking.protobuf.Base.NetHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.parking.protobuf.Base.NetHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * Protobuf type {@code com.parking.protobuf.NetHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.parking.protobuf.NetHeader)
        com.parking.protobuf.Base.NetHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.parking.protobuf.Base.NetHeader.class, com.parking.protobuf.Base.NetHeader.Builder.class);
      }

      // Construct using com.parking.protobuf.Base.NetHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        proto_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetHeader_descriptor;
      }

      public com.parking.protobuf.Base.NetHeader getDefaultInstanceForType() {
        return com.parking.protobuf.Base.NetHeader.getDefaultInstance();
      }

      public com.parking.protobuf.Base.NetHeader build() {
        com.parking.protobuf.Base.NetHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.parking.protobuf.Base.NetHeader buildPartial() {
        com.parking.protobuf.Base.NetHeader result = new com.parking.protobuf.Base.NetHeader(this);
        result.uid_ = uid_;
        result.proto_ = proto_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.parking.protobuf.Base.NetHeader) {
          return mergeFrom((com.parking.protobuf.Base.NetHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.parking.protobuf.Base.NetHeader other) {
        if (other == com.parking.protobuf.Base.NetHeader.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getProto().isEmpty()) {
          proto_ = other.proto_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.parking.protobuf.Base.NetHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.parking.protobuf.Base.NetHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       * 用户编号
       * </pre>
       *
       * <code>uint64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       * 用户编号
       * </pre>
       *
       * <code>uint64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户编号
       * </pre>
       *
       * <code>uint64 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object proto_ = "";
      /**
       * <pre>
       * 协议名称
       * </pre>
       *
       * <code>string proto = 2;</code>
       */
      public java.lang.String getProto() {
        java.lang.Object ref = proto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 协议名称
       * </pre>
       *
       * <code>string proto = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProtoBytes() {
        java.lang.Object ref = proto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 协议名称
       * </pre>
       *
       * <code>string proto = 2;</code>
       */
      public Builder setProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proto_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议名称
       * </pre>
       *
       * <code>string proto = 2;</code>
       */
      public Builder clearProto() {
        
        proto_ = getDefaultInstance().getProto();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议名称
       * </pre>
       *
       * <code>string proto = 2;</code>
       */
      public Builder setProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proto_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.parking.protobuf.NetHeader)
    }

    // @@protoc_insertion_point(class_scope:com.parking.protobuf.NetHeader)
    private static final com.parking.protobuf.Base.NetHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.parking.protobuf.Base.NetHeader();
    }

    public static com.parking.protobuf.Base.NetHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetHeader>
        PARSER = new com.google.protobuf.AbstractParser<NetHeader>() {
      public NetHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetHeader> getParserForType() {
      return PARSER;
    }

    public com.parking.protobuf.Base.NetHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.parking.protobuf.NetMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.parking.protobuf.NetHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.parking.protobuf.NetHeader header = 1;</code>
     */
    com.parking.protobuf.Base.NetHeader getHeader();
    /**
     * <code>.com.parking.protobuf.NetHeader header = 1;</code>
     */
    com.parking.protobuf.Base.NetHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.com.parking.protobuf.NetError error = 2;</code>
     */
    boolean hasError();
    /**
     * <code>.com.parking.protobuf.NetError error = 2;</code>
     */
    com.parking.protobuf.Base.NetError getError();
    /**
     * <code>.com.parking.protobuf.NetError error = 2;</code>
     */
    com.parking.protobuf.Base.NetErrorOrBuilder getErrorOrBuilder();

    /**
     * <code>bytes payload = 3;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * 游戏消息封装结构
   * </pre>
   *
   * Protobuf type {@code com.parking.protobuf.NetMessage}
   */
  public  static final class NetMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.parking.protobuf.NetMessage)
      NetMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetMessage.newBuilder() to construct.
    private NetMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetMessage() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.parking.protobuf.Base.NetHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.parking.protobuf.Base.NetHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.parking.protobuf.Base.NetError.Builder subBuilder = null;
              if (error_ != null) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(com.parking.protobuf.Base.NetError.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.parking.protobuf.Base.NetMessage.class, com.parking.protobuf.Base.NetMessage.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.parking.protobuf.Base.NetHeader header_;
    /**
     * <code>.com.parking.protobuf.NetHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.parking.protobuf.NetHeader header = 1;</code>
     */
    public com.parking.protobuf.Base.NetHeader getHeader() {
      return header_ == null ? com.parking.protobuf.Base.NetHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.parking.protobuf.NetHeader header = 1;</code>
     */
    public com.parking.protobuf.Base.NetHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private com.parking.protobuf.Base.NetError error_;
    /**
     * <code>.com.parking.protobuf.NetError error = 2;</code>
     */
    public boolean hasError() {
      return error_ != null;
    }
    /**
     * <code>.com.parking.protobuf.NetError error = 2;</code>
     */
    public com.parking.protobuf.Base.NetError getError() {
      return error_ == null ? com.parking.protobuf.Base.NetError.getDefaultInstance() : error_;
    }
    /**
     * <code>.com.parking.protobuf.NetError error = 2;</code>
     */
    public com.parking.protobuf.Base.NetErrorOrBuilder getErrorOrBuilder() {
      return getError();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (error_ != null) {
        output.writeMessage(2, getError());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(3, payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (error_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getError());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.parking.protobuf.Base.NetMessage)) {
        return super.equals(obj);
      }
      com.parking.protobuf.Base.NetMessage other = (com.parking.protobuf.Base.NetMessage) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.parking.protobuf.Base.NetMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parking.protobuf.Base.NetMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.parking.protobuf.Base.NetMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 游戏消息封装结构
     * </pre>
     *
     * Protobuf type {@code com.parking.protobuf.NetMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.parking.protobuf.NetMessage)
        com.parking.protobuf.Base.NetMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.parking.protobuf.Base.NetMessage.class, com.parking.protobuf.Base.NetMessage.Builder.class);
      }

      // Construct using com.parking.protobuf.Base.NetMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (errorBuilder_ == null) {
          error_ = null;
        } else {
          error_ = null;
          errorBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.parking.protobuf.Base.internal_static_com_parking_protobuf_NetMessage_descriptor;
      }

      public com.parking.protobuf.Base.NetMessage getDefaultInstanceForType() {
        return com.parking.protobuf.Base.NetMessage.getDefaultInstance();
      }

      public com.parking.protobuf.Base.NetMessage build() {
        com.parking.protobuf.Base.NetMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.parking.protobuf.Base.NetMessage buildPartial() {
        com.parking.protobuf.Base.NetMessage result = new com.parking.protobuf.Base.NetMessage(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.parking.protobuf.Base.NetMessage) {
          return mergeFrom((com.parking.protobuf.Base.NetMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.parking.protobuf.Base.NetMessage other) {
        if (other == com.parking.protobuf.Base.NetMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.parking.protobuf.Base.NetMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.parking.protobuf.Base.NetMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.parking.protobuf.Base.NetHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.parking.protobuf.Base.NetHeader, com.parking.protobuf.Base.NetHeader.Builder, com.parking.protobuf.Base.NetHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public com.parking.protobuf.Base.NetHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.parking.protobuf.Base.NetHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public Builder setHeader(com.parking.protobuf.Base.NetHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public Builder setHeader(
          com.parking.protobuf.Base.NetHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public Builder mergeHeader(com.parking.protobuf.Base.NetHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.parking.protobuf.Base.NetHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public com.parking.protobuf.Base.NetHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      public com.parking.protobuf.Base.NetHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.parking.protobuf.Base.NetHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.parking.protobuf.NetHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.parking.protobuf.Base.NetHeader, com.parking.protobuf.Base.NetHeader.Builder, com.parking.protobuf.Base.NetHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.parking.protobuf.Base.NetHeader, com.parking.protobuf.Base.NetHeader.Builder, com.parking.protobuf.Base.NetHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.parking.protobuf.Base.NetError error_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.parking.protobuf.Base.NetError, com.parking.protobuf.Base.NetError.Builder, com.parking.protobuf.Base.NetErrorOrBuilder> errorBuilder_;
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public boolean hasError() {
        return errorBuilder_ != null || error_ != null;
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public com.parking.protobuf.Base.NetError getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? com.parking.protobuf.Base.NetError.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public Builder setError(com.parking.protobuf.Base.NetError value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public Builder setError(
          com.parking.protobuf.Base.NetError.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public Builder mergeError(com.parking.protobuf.Base.NetError value) {
        if (errorBuilder_ == null) {
          if (error_ != null) {
            error_ =
              com.parking.protobuf.Base.NetError.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = null;
          onChanged();
        } else {
          error_ = null;
          errorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public com.parking.protobuf.Base.NetError.Builder getErrorBuilder() {
        
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      public com.parking.protobuf.Base.NetErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              com.parking.protobuf.Base.NetError.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.com.parking.protobuf.NetError error = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.parking.protobuf.Base.NetError, com.parking.protobuf.Base.NetError.Builder, com.parking.protobuf.Base.NetErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.parking.protobuf.Base.NetError, com.parking.protobuf.Base.NetError.Builder, com.parking.protobuf.Base.NetErrorOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 3;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 3;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 3;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.parking.protobuf.NetMessage)
    }

    // @@protoc_insertion_point(class_scope:com.parking.protobuf.NetMessage)
    private static final com.parking.protobuf.Base.NetMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.parking.protobuf.Base.NetMessage();
    }

    public static com.parking.protobuf.Base.NetMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessage>
        PARSER = new com.google.protobuf.AbstractParser<NetMessage>() {
      public NetMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessage> getParserForType() {
      return PARSER;
    }

    public com.parking.protobuf.Base.NetMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_parking_protobuf_NetError_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_parking_protobuf_NetError_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_parking_protobuf_NetHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_parking_protobuf_NetHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_parking_protobuf_NetMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_parking_protobuf_NetMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobuf/base.proto\022\024com.parking.proto" +
      "buf\"\030\n\010NetError\022\014\n\004code\030\001 \001(\r\"\'\n\tNetHead" +
      "er\022\013\n\003uid\030\001 \001(\004\022\r\n\005proto\030\002 \001(\t\"}\n\nNetMes" +
      "sage\022/\n\006header\030\001 \001(\0132\037.com.parking.proto" +
      "buf.NetHeader\022-\n\005error\030\002 \001(\0132\036.com.parki" +
      "ng.protobuf.NetError\022\017\n\007payload\030\003 \001(\014b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_parking_protobuf_NetError_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_parking_protobuf_NetError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_parking_protobuf_NetError_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_parking_protobuf_NetHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_parking_protobuf_NetHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_parking_protobuf_NetHeader_descriptor,
        new java.lang.String[] { "Uid", "Proto", });
    internal_static_com_parking_protobuf_NetMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_parking_protobuf_NetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_parking_protobuf_NetMessage_descriptor,
        new java.lang.String[] { "Header", "Error", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
